name: first_workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Display message
        run: echo "Hello, World!"
      - name: Step 2 - Display another message
        run: echo "Hello, David the man!"
